CREATE TABLE PACIENTE (

	 
     NOME VARCHAR (50) NOT NULL,
     RG VARCHAR(20) NOT NULL,
     CPF VARCHAR(20) UNIQUE,
     TELEFONE VARCHAR (20) NULL,
     ESTADO VARCHAR(20) NULL,
     CIDADE VARCHAR(30) NULL,
     BAIRRO VARCHAR (30) NULL,
     RUA VARCHAR (30) NULL,
     NUMERO INT NULL,
     
     PRIMARY KEY (CPF)
     
);


CREATE TABLE FUNCIONARIO (
	 
     NOME VARCHAR (50) NOT NULL,
     RG VARCHAR(20) NOT NULL,
     CPF VARCHAR(20) UNIQUE,
     TELEFONE VARCHAR (20) NULL,
     ESTADO VARCHAR(30) NULL,
     CIDADE VARCHAR(30) NULL,
     BAIRRO VARCHAR (30) NULL,
     RUA VARCHAR (30) NULL,
     NUMERO INT NULL,
     LOGIN VARCHAR(30) UNIQUE,
     SENHA VARCHAR (30) NULL,
     
     PRIMARY KEY (CPF)
  );
  
  CREATE TABLE DADOSAGENDAMENTO(
	
    NOMEPACIENTE VARCHAR(50),
    CPFPACIENTE VARCHAR(20),
    HORARIO VARCHAR(10),
    DATAAGENDAMENTO VARCHAR(12),
    
    PRIMARY KEY (DATAAGENDAMENTO, HORARIO)
  
  );
  
    
  CREATE TABLE AGENDAMENTO(
  
	DATAAGENDAMENTO VARCHAR(12),
    CPFPACIENTE VARCHAR (20),
	PRIMARY KEY (DATAAGENDAMENTO, CPFPACIENTE)    
  
  );
  
  CREATE TABLE PRONTUARIO(
  
	HISTORICO VARCHAR(300),
    CPFPACIENTE VARCHAR(20),
    
    PRIMARY KEY (CPFPACIENTE)
  
  );
  
  
